#!/usr/bin/env -S bash -e
# pre-commit hook for the current Git repository.

# shellcheck source=lib/functions
. ./.githooks/lib/functions

run_git_diff() {
    cd "${git_sync_repo}"
    git add -A
    PAGER="" git diff --cached
    PAGER="" git diff
}

run_health_check() {
    run_git_diff
}

cleanup() {
    exit_code="${1}"
    if [[ "${exit_code}" -ne 0 ]]
    then
        print_fail "Something went wrong with git config or with healthcheck! Exit code: ${exit_code}"
        # shellcheck disable=2086
        exit ${exit_code}
    fi
    # shellcheck disable=2086
    exit ${exit_code}
}

trap "cleanup" EXIT

print_info "Hello, ${username}, let's try to sync your changes."

print_info "Run healthcheck"
run_health_check

print_okay "Healthcheck is OK!"
